# Generated by Django 3.1.1 on 2020-11-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField()),
                ('playlist_title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('songs', models.CharField(max_length=300)),
                ('like_cnt', models.IntegerField()),
                ('updt_date', models.DateTimeField()),
            ],
        ),
    ]
