# Generated by Django 3.1.1 on 2020-11-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0002_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongMeta',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('album_id', models.IntegerField(blank=True, null=True)),
                ('album_name', models.CharField(blank=True, max_length=200, null=True)),
                ('aritst_id_basket', models.CharField(blank=True, max_length=200, null=True)),
                ('artist_name_basket', models.CharField(blank=True, max_length=200, null=True)),
                ('song_name', models.CharField(blank=True, max_length=200, null=True)),
                ('song_gn_gnr_basket', models.CharField(blank=True, max_length=200, null=True)),
                ('song_gn_dtl_gnr_basket', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('url_link', models.CharField(blank=True, max_length=300, null=True)),
                ('album_image', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'song_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age_group', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='ReactionTable',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='musicApp.userinfo')),
                ('reaction_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reaction_table',
                'managed': False,
            },
        ),
    ]
