# Generated by Django 3.1.1 on 2020-11-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0003_auto_20201119_1500'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='playlist',
        ),
    ]
